### ISSUE TITLE
If the image is bigger enough,  it will be covered by the sidebar on the left.

### ISSUE THREAD

**Issue by dyonghan** [qq915458022/gitbook-plugin-image-viewer#1]
If the image is bigger enough,  it will be covered by the sidebar on the left when the image is zoom out.

**Comment by tearfulDalvik** [comment]
I used this in an electron project. The resolution is using shell instead of a javascript library.
Also, you can replace this js library simply :)

**Comment by tearfulDalvik** [comment]
and... sorry for being late, feel free to reopen it if you have any questions.
